"""Add assignment fields

Revision ID: 6541f4fd8003
Revises: b68064f6ddee
Create Date: 2026-06-27 21:44:31.228294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6541f4fd8003'
down_revision: Union[str, Sequence[str], None] = 'b68064f6ddee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('assignee_id', sa.Integer(), nullable=True))
    op.add_column('issues', sa.Column('assigned_at', sa.DateTime(), nullable=True))
    op.add_column('issues', sa.Column('reporter_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'issues', 'users', ['reporter_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'issues', 'users', ['assignee_id'], ['id'], ondelete='SET NULL')
    op.add_column('test_cases', sa.Column('is_manual', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('test_cases', sa.Column('assignee_id', sa.Integer(), nullable=True))
    op.add_column('test_cases', sa.Column('assigned_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'test_cases', 'users', ['assignee_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_cases', type_='foreignkey')
    op.drop_column('test_cases', 'assigned_at')
    op.drop_column('test_cases', 'assignee_id')
    op.drop_column('test_cases', 'is_manual')
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_column('issues', 'reporter_id')
    op.drop_column('issues', 'assigned_at')
    op.drop_column('issues', 'assignee_id')
    # ### end Alembic commands ###
