"""Add Phase 6.6 Notification fields and preferences

Revision ID: e27dc0db6d98
Revises: d135ee536a6e
Create Date: 2026-07-01 14:04:02.907515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e27dc0db6d98'
down_revision: Union[str, Sequence[str], None] = 'd135ee536a6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('via_email', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'type', name='uq_user_id_type')
    )
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=False)
    op.add_column('notifications', sa.Column('entity_type', sa.String(length=50), nullable=True))
    op.add_column('notifications', sa.Column('entity_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('org_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notifications', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'notifications', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_organization_members_org_id'), table_name='organization_members')
    op.drop_constraint(op.f('uq_org_member'), 'organization_members', type_='unique')
    op.create_index(op.f('ix_organization_members_organization_id'), 'organization_members', ['organization_id'], unique=False)
    op.drop_constraint(op.f('uq_team_member'), 'team_members', type_='unique')
    op.drop_constraint(op.f('uq_team_org_name'), 'teams', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_team_org_name'), 'teams', ['organization_id', 'name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_team_member'), 'team_members', ['team_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_organization_members_organization_id'), table_name='organization_members')
    op.create_unique_constraint(op.f('uq_org_member'), 'organization_members', ['organization_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_organization_members_org_id'), 'organization_members', ['organization_id'], unique=False)
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'org_id')
    op.drop_column('notifications', 'project_id')
    op.drop_column('notifications', 'entity_id')
    op.drop_column('notifications', 'entity_type')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    # ### end Alembic commands ###
